services:
  Rayenbou\DashboardBundle\Command\SecurityCommand:
    tags:
      - { name: "console.command" }
  Rayenbou\DashboardBundle\Controller\TicketDashboardController:
    tags:
      - { name: "controller.service_arguments" }
      - { name: "container.service_subscriber" }
    arguments:
      - Rayenbou\DashboardBundle\Repository\TicketRepository: "@rayenbou_ticket.ticket_repository"
      - Rayenbou\DashboardBundle\Entity\Ticket: "@rayenbou_ticket.ticket_entity"
      - Rayenbou\DashboardBundle\Entity\TicketMessage: "@rayenbou_ticket.ticket_message_entity"
    public: true
    autowire: true
    autoconfigure: true
    # pour pouvoir injecter les service de l'abstract controller et utiliser ses methode
    # il ne faut pas preciser d'argument a la methode setContainer pour laisser l'injection de dependance
    # se faire automatiquement. il faut juste preciser un tableau vide
    calls:
      - method: setContainer
        arguments: [""]
